# -*- coding: utf-8 -*-
"""OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFbJF2dD5h7cRZuxtn0M6Yp3BsQboFc7
"""

import cv2
print(cv2.__version__)

import cv2
img = cv2.imread('surface.jpg')
print('Image Shape : ',img.shape)
gray =cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print('Grayscale Shape :',gray.shape)

edges = cv2.Canny(gray ,50,150)
print("Edges Shape ; ",edges.shape)

cv2.imwrite('grayscale.jpg', gray)
cv2.imwrite('edges.jpg', edges)
print("Images saved!")
result = img.copy()
result[edges !=0] = [0,0,255]
cv2.imwrite('defects_highlighted.jpg',result)
print("defect highlighted image saved!")
print("defective pixels found : ",edges[edges!=0].size)